import { type Invitation } from "./InvitationCard";

export const initialInvitations: Invitation[] = [
  {
    id: "1",
    salonName: "Elegance Spa",
    senderName: "Sarah Johnson",
    message: "We would love to have you as our accountant",
    sentDate: "Jun 14, 2025",
  },
  {
    id: "2",
    salonName: "Urban Hair Studio",
    senderName: "Mike Davis",
    message: "Looking for a reliable tax advisor",
    sentDate: "Jun 14, 2025",
  },
];

export interface SalonInfo {
  id: string;
  name: string;
  badge: string;
  ownerName: string;
  city: string;
  email: string;
  plan: "Premium" | "Enterprise" | "Basic";
  planPrice: string;
  paymentStatus: "In order" | "Late";
  nextRenewal: string;
  referral: string;
  avatarGradient: string;
  avatarImage?: string;
}

export const salonsData: SalonInfo[] = [
  {
    id: "1",
    name: "Beauty Wellness Center",
    badge: "SRL",
    ownerName: "Roberto Marini",
    city: "Bologna",
    email: "roberto@beautywellness.com",
    plan: "Premium",
    planPrice: "Annual • €2,000.00 / year",
    paymentStatus: "In order",
    nextRenewal: "Dec 01, 2024",
    referral: "30%",
    avatarGradient: "from-blue-200 via-orange-100 to-purple-200",
    avatarImage: "/RecentActivity/RecentActivity1.png",
  },
  {
    id: "2",
    name: "Bella Vista Salon",
    badge: "SRL",
    ownerName: "Maria Rodriguez",
    city: "Milano",
    email: "maria@bellavista.com",
    plan: "Premium",
    planPrice: "Annual • €2,000.00 / year",
    paymentStatus: "In order",
    nextRenewal: "Dec 01, 2024",
    referral: "30%",
    avatarGradient: "from-purple-500 via-pink-400 to-blue-400",
    avatarImage: "/RecentActivity/RecentActivity2.png",
  },
  {
    id: "3",
    name: "Elite Beauty Group S.p.A.",
    badge: "SPA",
    ownerName: "Dr. Marco Rossi",
    city: "Milano",
    email: "marco.rossi@elitebeauty.com",
    plan: "Enterprise",
    planPrice: "Annual • €3,000.00 / year",
    paymentStatus: "In order",
    nextRenewal: "Dec 01, 2024",
    referral: "-",
    avatarGradient: "from-blue-300 via-green-100 to-yellow-100",
    avatarImage: "/RecentActivity/RecentActivity1.png",
  },
  {
    id: "4",
    name: "Glamour Lounge SRLS",
    badge: "SRLS",
    ownerName: "Anna Bianchi",
    city: "Torino",
    email: "anna@glamourlounge.com",
    plan: "Premium",
    planPrice: "Annual • €2,000.00 / year",
    paymentStatus: "Late",
    nextRenewal: "Dec 01, 2024",
    referral: "30%",
    avatarGradient: "from-pink-400 via-purple-300 to-orange-300",
    avatarImage: "/RecentActivity/RecentActivity2.png",
  },
  {
    id: "5",
    name: "Hair Art Studio",
    badge: "Ind.",
    ownerName: "Francesca Neri",
    city: "Roma",
    email: "francesca@hairartstudio.com",
    plan: "Basic",
    planPrice: "Annual • €1,000.00 / year",
    paymentStatus: "Late",
    nextRenewal: "Dec 01, 2024",
    referral: "30%",
    avatarGradient: "from-blue-200 via-indigo-200 to-purple-200",
    avatarImage: "/RecentActivity/RecentActivity1.png",
  },
  {
    id: "6",
    name: "Luxury Nails & Spa",
    badge: "SRL",
    ownerName: "Chiara Ferrari",
    city: "Napoli",
    email: "chiara@luxurynails.com",
    plan: "Premium",
    planPrice: "Annual • €2,000.00 / year",
    paymentStatus: "In order",
    nextRenewal: "Jan 15, 2025",
    referral: "15%",
    avatarGradient: "from-pink-300 via-purple-300 to-indigo-400",
  },
  {
    id: "7",
    name: "Studio Estetica 2000",
    badge: "SNC",
    ownerName: "Giuseppe Romano",
    city: "Firenze",
    email: "giuseppe@estetica2000.it",
    plan: "Basic",
    planPrice: "Annual • €1,000.00 / year",
    paymentStatus: "In order",
    nextRenewal: "Feb 20, 2025",
    referral: "-",
    avatarGradient: "from-green-200 via-teal-300 to-blue-400",
  },
  {
    id: "8",
    name: "Barberia Centrale",
    badge: "Ind.",
    ownerName: "Luigi Costa",
    city: "Venezia",
    email: "luigi@barberiacentrale.it",
    plan: "Basic",
    planPrice: "Annual • €1,000.00 / year",
    paymentStatus: "Late",
    nextRenewal: "Oct 10, 2024",
    referral: "10%",
    avatarGradient: "from-yellow-200 via-orange-300 to-red-400",
  },
  {
    id: "9",
    name: "Urban Oasis Spa",
    badge: "SRL",
    ownerName: "Elena Moretti",
    city: "Genova",
    email: "elena@urbanoasis.com",
    plan: "Enterprise",
    planPrice: "Annual • €3,000.00 / year",
    paymentStatus: "In order",
    nextRenewal: "Mar 05, 2025",
    referral: "20%",
    avatarGradient: "from-blue-400 via-indigo-500 to-purple-600",
  },
  {
    id: "10",
    name: "Capelli Perfetti",
    badge: "SAS",
    ownerName: "Antonio Russo",
    city: "Palermo",
    email: "antonio@capelliperfetti.it",
    plan: "Premium",
    planPrice: "Annual • €2,000.00 / year",
    paymentStatus: "In order",
    nextRenewal: "Apr 12, 2025",
    referral: "15%",
    avatarGradient: "from-red-200 via-pink-300 to-purple-400",
  },
  {
    id: "11",
    name: "Glow & Go",
    badge: "SRL",
    ownerName: "Martina Conti",
    city: "Bari",
    email: "martina@glowandgo.it",
    plan: "Basic",
    planPrice: "Annual • €1,000.00 / year",
    paymentStatus: "In order",
    nextRenewal: "May 18, 2025",
    referral: "-",
    avatarGradient: "from-cyan-200 via-blue-300 to-indigo-400",
  },
  {
    id: "12",
    name: "Il Salotto della Bellezza",
    badge: "SPA",
    ownerName: "Alessia Rizzo",
    city: "Catania",
    email: "alessia@salottobellezza.it",
    plan: "Enterprise",
    planPrice: "Annual • €3,000.00 / year",
    paymentStatus: "In order",
    nextRenewal: "Jun 22, 2025",
    referral: "25%",
    avatarGradient: "from-fuchsia-200 via-pink-300 to-red-300",
  },
  {
    id: "13",
    name: "Moda Capelli",
    badge: "SNC",
    ownerName: "Simone Santoro",
    city: "Verona",
    email: "simone@modacapelli.com",
    plan: "Premium",
    planPrice: "Annual • €2,000.00 / year",
    paymentStatus: "Late",
    nextRenewal: "Sep 30, 2024",
    referral: "10%",
    avatarGradient: "from-violet-200 via-purple-300 to-fuchsia-400",
  },
  {
    id: "14",
    name: "Pura Vida Spa",
    badge: "SRLS",
    ownerName: "Valeria Lombardi",
    city: "Messina",
    email: "valeria@puravidaspa.it",
    plan: "Premium",
    planPrice: "Annual • €2,000.00 / year",
    paymentStatus: "In order",
    nextRenewal: "Jul 11, 2025",
    referral: "20%",
    avatarGradient: "from-green-300 via-emerald-400 to-teal-500",
  },
  {
    id: "15",
    name: "Stile e Colore",
    badge: "Ind.",
    ownerName: "Davide Marino",
    city: "Padova",
    email: "davide@stileecolore.it",
    plan: "Basic",
    planPrice: "Annual • €1,000.00 / year",
    paymentStatus: "In order",
    nextRenewal: "Aug 05, 2025",
    referral: "-",
    avatarGradient: "from-yellow-300 via-orange-400 to-red-500",
  },
  {
    id: "16",
    name: "La Dolce Vita Salon",
    badge: "SRL",
    ownerName: "Sara Greco",
    city: "Trieste",
    email: "sara@ladolcevitasalon.com",
    plan: "Enterprise",
    planPrice: "Annual • €3,000.00 / year",
    paymentStatus: "In order",
    nextRenewal: "Nov 15, 2024",
    referral: "30%",
    avatarGradient: "from-red-300 via-rose-400 to-pink-500",
  },
  {
    id: "17",
    name: "Natura e Bellezza",
    badge: "SAS",
    ownerName: "Paolo Gallo",
    city: "Brescia",
    email: "paolo@naturabellezza.it",
    plan: "Premium",
    planPrice: "Annual • €2,000.00 / year",
    paymentStatus: "Late",
    nextRenewal: "Oct 20, 2024",
    referral: "15%",
    avatarGradient: "from-teal-200 via-cyan-300 to-blue-400",
  },
  {
    id: "18",
    name: "L'Arte del Taglio",
    badge: "SNC",
    ownerName: "Marta Fabbri",
    city: "Parma",
    email: "marta@artedeltaglio.it",
    plan: "Basic",
    planPrice: "Annual • €1,000.00 / year",
    paymentStatus: "In order",
    nextRenewal: "Dec 10, 2024",
    referral: "-",
    avatarGradient: "from-indigo-200 via-blue-300 to-cyan-400",
  },
  {
    id: "19",
    name: "Benessere Totale",
    badge: "SRLS",
    ownerName: "Luca Esposito",
    city: "Prato",
    email: "luca@benesseretotale.com",
    plan: "Premium",
    planPrice: "Annual • €2,000.00 / year",
    paymentStatus: "In order",
    nextRenewal: "Jan 25, 2025",
    referral: "20%",
    avatarGradient: "from-orange-200 via-amber-300 to-yellow-400",
  },
  {
    id: "20",
    name: "Vogue Estetica",
    badge: "SPA",
    ownerName: "Giulia Coppola",
    city: "Taranto",
    email: "giulia@vogueestetica.it",
    plan: "Enterprise",
    planPrice: "Annual • €3,000.00 / year",
    paymentStatus: "In order",
    nextRenewal: "Feb 28, 2025",
    referral: "25%",
    avatarGradient: "from-pink-200 via-rose-300 to-red-400",
  }
];

export const mockInvitations = [
  {
    id: 1,
    salonName: "Beauty Wellness Center",
    email: "roberto@beautywellness.com",
    date: "Dec 01, 2024",
    status: "Accepted",
    plan: "Premium",
    planDetails: "Annual • €2,000.00 /year",
    share: "€ 600",
    lastShare: "Last: € 600",
    avatarGradient: "from-[#FFC371] to-[#FF5F6D]",
  },
  {
    id: 2,
    salonName: "Bella Vista Salon",
    email: "maria@bellavista.com",
    date: "Dec 01, 2024",
    status: "Accepted",
    plan: "Premium",
    planDetails: "Annual • €2,000.00 /year",
    share: "€ 600",
    lastShare: "Last: € 600",
    avatarGradient: "from-[#00C9FF] to-[#92FE9D]",
  },
  {
    id: 3,
    salonName: "Elite Beauty Group S.p.A.",
    email: "marco.rossi@elitebeauty.com",
    date: "Dec 01, 2024",
    status: "Accepted",
    plan: "Enterprise",
    planDetails: "Annual • €3,000.00 /year",
    share: "-",
    lastShare: "-",
    avatarGradient: "from-[#8E2DE2] to-[#4A00E0]",
  },
  {
    id: 4,
    salonName: "Glamour Lounge SRLS",
    email: "anna@glamourlounge.com",
    date: "Dec 01, 2024",
    status: "Pending",
    plan: "-",
    planDetails: "-",
    share: "-",
    lastShare: "-",
    avatarGradient: "from-[#f12711] to-[#f5af19]",
  },
  {
    id: 5,
    salonName: "Hair Art Studio",
    email: "francesca@hairartstudio.com",
    date: "Dec 01, 2024",
    status: "Rejected",
    plan: "-",
    planDetails: "-",
    share: "-",
    lastShare: "-",
    avatarGradient: "from-[#a18cd1] to-[#fbc2eb]",
  },
];
